### ISSUE TITLE
Bug al ejecutar make

### ISSUE THREAD

**Issue by tanrax** [saul-g/El-libro-de-Django#4]
Lo he intentado tanto en Debian como en OS X, y cuando ejecutas `make html`, o `make epub` te encuentras con el siguiente error.

```
    StandaloneHTMLBuilder.init(self)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/html.py", line 107, in init
    self.init_highlighter()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/html.py", line 155, in init_highlighter
    self.config.trim_doctest_flags)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/highlighting.py", line 78, in __init__
    style = get_style_by_name(stylename)
  File "/usr/local/lib/python2.7/dist-packages/pygments/styles/__init__.py", line 61, in get_style_by_name
    (builtin and ", though it should be builtin") + ".")
ClassNotFound: Could not find style module 'matizze'.
```

**Comment by fgalvanbaez** [comment]
Me aparece el mismo error. El siguiente código es la raza completa que se puede encontrar en: /tmp/sphinx-err-xdnNJi.log en mi caso.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/**init**.py", line 240, in build_update
    self.build(['**all**'], to_build)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/**init**.py", line 316, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/latex.py", line 107, in write
    docwriter.write(doctree, destination)
  File "/usr/local/lib/python2.7/dist-packages/docutils/writers/**init**.py", line 80, in write
    self.translate()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/writers/latex.py", line 100, in translate
    visitor = self.translator_class(self.document, self.builder)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/writers/latex.py", line 260, in **init**
    builder.config.pygments_style, builder.config.trim_doctest_flags)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/highlighting.py", line 78, in **init**
    style = get_style_by_name(stylename)
  File "/usr/local/lib/python2.7/dist-packages/pygments/styles/**init**.py", line 61, in get_style_by_name
    (builtin and ", though it should be builtin") + ".")

**Comment by EduardoZepeda** [comment]
Yo solucioné el problema de la siguiente manera: 
Vayan al archivo llamado "conf.py", abranlo y encuentren lo siguiente:

> Options for HTML output.
> ...
> pygments_style = 'matizze'
> ...

Sustituyan la palabra 'matizze' por 'default', debe quedar así: 

> pygments_style = 'default'

Guarden el archivo e intenten correr de nuevo el comando make html o make epub desde la consola
Adjunto una captura de pantalla del archivo conf.py modificado. 

![captura de pantalla de 2015-06-30 13 31 21](https://cloud.githubusercontent.com/assets/13123220/8438571/5d4c3f4e-1f2c-11e5-8e1a-21cbac8cb2bf.png)

**Comment by tanrax** [comment]
Va perfecto!!! Ya he enviado un pull request con el cambio.
